// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ContractAlpha.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Contracts.Grpc.Alpha {
  public static partial class AlphaService
  {
    static readonly string __ServiceName = "contracts.grpc.alpha.AlphaService";

    static readonly grpc::Marshaller<global::Contracts.Grpc.Alpha.GetAlphaByIdRequest> __Marshaller_contracts_grpc_alpha_GetAlphaByIdRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Contracts.Grpc.Alpha.GetAlphaByIdRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Contracts.Grpc.Alpha.GetAlphaByIdResponse> __Marshaller_contracts_grpc_alpha_GetAlphaByIdResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Contracts.Grpc.Alpha.GetAlphaByIdResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Contracts.Grpc.Alpha.GetAlphaByIdRequest, global::Contracts.Grpc.Alpha.GetAlphaByIdResponse> __Method_GetAlphaById = new grpc::Method<global::Contracts.Grpc.Alpha.GetAlphaByIdRequest, global::Contracts.Grpc.Alpha.GetAlphaByIdResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAlphaById",
        __Marshaller_contracts_grpc_alpha_GetAlphaByIdRequest,
        __Marshaller_contracts_grpc_alpha_GetAlphaByIdResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Contracts.Grpc.Alpha.ContractAlphaReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AlphaService</summary>
    public abstract partial class AlphaServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Contracts.Grpc.Alpha.GetAlphaByIdResponse> GetAlphaById(global::Contracts.Grpc.Alpha.GetAlphaByIdRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AlphaService</summary>
    public partial class AlphaServiceClient : grpc::ClientBase<AlphaServiceClient>
    {
      /// <summary>Creates a new client for AlphaService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AlphaServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AlphaService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AlphaServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AlphaServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AlphaServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Contracts.Grpc.Alpha.GetAlphaByIdResponse GetAlphaById(global::Contracts.Grpc.Alpha.GetAlphaByIdRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAlphaById(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Contracts.Grpc.Alpha.GetAlphaByIdResponse GetAlphaById(global::Contracts.Grpc.Alpha.GetAlphaByIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAlphaById, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Contracts.Grpc.Alpha.GetAlphaByIdResponse> GetAlphaByIdAsync(global::Contracts.Grpc.Alpha.GetAlphaByIdRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAlphaByIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Contracts.Grpc.Alpha.GetAlphaByIdResponse> GetAlphaByIdAsync(global::Contracts.Grpc.Alpha.GetAlphaByIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAlphaById, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AlphaServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AlphaServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AlphaServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetAlphaById, serviceImpl.GetAlphaById).Build();
    }

  }
}
#endregion
